---
- name: Clone Vundle repository
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: /home/willian/.vim/bundle/Vundle.vim
  become: true
  become_user: willian
  tags:
    - skip_ansible_lint
    - vim
